version: "3"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gorm_crud
    container_name: golang_db
    ports:
      - "3307:3306"
    networks:
      - golang
    tty: true
  app:
    build:
      context: .
    command: go run main.go
    volumes:
      - go_storage:/go_storage
    container_name: golang_app
    ports:
      - "8002:8000"
    depends_on:
      - db
    networks:
      - golang
    tty: true
networks:
  golang:
volumes:
  go_storage:
