### GET ALL USERS
GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjQxOTA5NDYsImlkIjoxNiwibmFtZSI6Ik1hbWF0In0.rfAArsKE_m36hRONqfYUQ0pT-ARz6wa7Y7rqmvnRUV8

### GET USER
GET http://localhost:8000/users/19

### INSERT USER
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Mamat",
    "email": "mamat@gmail.com",
    "password": "123456"
}

### DELETE USER
DELETE  http://localhost:8000/users/19f

### PUT USER
PUT http://localhost:8000/users/17f
Content-Type: application/json

{
    "name": "234",
    "email": "m@gmail.com",
    "password": "1234"
}

### GET ALL BOOKS
GET http://localhost:8000/books

### GET BOOK
GET http://localhost:8000/books/21

### INSERT BOOK
POST http://localhost:8000/books
Content-Type: application/json

{
    "title": "Bat Man",
    "author": "Jack Spar",
    "description": "Buku Bat man"
}

### DELETE BOOK
DELETE  http://localhost:8000/books/3

### PUT BOOK
PUT http://localhost:8000/books/2
Content-Type: application/json

{
    "title": "Aqua Man",
    "author": "Peri",
    "description": "Sang Raja lautan"
}