### GET ALL USERS
GET http://localhost:8000/
### GET ALL USERS
GET http://coco.go-rest-api.live/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjYxODA2NDQsImlkIjoxOSwiaXNzIjoicXdlcnR5IiwibmFtZSI6Ik1hbWF0MTIzIn0.O8qxwXEU2uM9y3JYW1IDFPU2pLxLdoKTDymBvYvwwCc

### GET USER
GET https://localhost:8000/users/23
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjQ3MTI5NzksImlkIjozNywiaXNzIjoicXdlcnR5IiwibmFtZSI6Ik1hbWF0MTIzIn0.k2p0-PNBPcdbz9eb2JM7tbXbJYiqapmj85E6B_0IkNI

### INSERT USER
POST http://coco.go-rest-api.live/users
Content-Type: application/json

{
    "name": "Mamat123",
    "email": "mamat@gmail.com",
    "password": "123456"
}

### DELETE USER
DELETE  http://localhost:8000/users/22
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjQ3MTI5NzksImlkIjozNywiaXNzIjoicXdlcnR5IiwibmFtZSI6Ik1hbWF0MTIzIn0.k2p0-PNBPcdbz9eb2JM7tbXbJYiqapmj85E6B_0IkNI

### PUT USER
PUT http://localhost:8000/users/23
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjQ3MTI5NzksImlkIjozNywiaXNzIjoicXdlcnR5IiwibmFtZSI6Ik1hbWF0MTIzIn0.k2p0-PNBPcdbz9eb2JM7tbXbJYiqapmj85E6B_0IkNI

{
    "name": "234",
    "email": "m@gmail.com",
    "password": "1234"
}

### GET ALL BOOKS
GET http://coco.go-rest-api.live/books

### GET BOOK
GET http://coco.go-rest-api.live/books/8

### INSERT BOOK
POST http://coco.go-rest-api.live/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjYxOTYwMjcsImlkIjoyMSwiaXNzIjoicXdlcnR5IiwibmFtZSI6Ik1hbWF0MTIzIn0.0sj_oACZ-PHz0CDd8FX3qzzn9j3W6Qp7FOiIwyoLc0o

{
    "title": "Bat Man 123",
    "author": "Jack Spar 123",
    "description": "Buku Bat man"
}

### DELETE BOOK
DELETE  http://localhost:8000/books/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjQ3MTI5NzksImlkIjozNywiaXNzIjoicXdlcnR5IiwibmFtZSI6Ik1hbWF0MTIzIn0.k2p0-PNBPcdbz9eb2JM7tbXbJYiqapmj85E6B_0IkNI

### PUT BOOK
PUT http://localhost:8000/books/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjQ3MTI5NzksImlkIjozNywiaXNzIjoicXdlcnR5IiwibmFtZSI6Ik1hbWF0MTIzIn0.k2p0-PNBPcdbz9eb2JM7tbXbJYiqapmj85E6B_0IkNI

{
    "title": "Aqua Man",
    "author": "Peri",
    "description": "Sang Raja lautan"
}