### GET ALL USERS
GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjQzMDMyMzksImlkIjoyNCwibmFtZSI6Ik1hbWF0In0.Y96EzfmV58SLiFFqbS2ibO8_50m9usMFfMGkZ56MDco

### GET USER
GET http://localhost:8000/users/22
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjQzMDMyMzksImlkIjoyNCwibmFtZSI6Ik1hbWF0In0.Y96EzfmV58SLiFFqbS2ibO8_50m9usMFfMGkZ56MDco

### INSERT USER
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Mamat123",
    "email": "mamat@gmail.com",
    "password": "123456"
}

### DELETE USER
DELETE  http://localhost:8000/users/19f

### PUT USER
PUT http://localhost:8000/users/17f
Content-Type: application/json

{
    "name": "234",
    "email": "m@gmail.com",
    "password": "1234"
}

### GET ALL BOOKS
GET http://localhost:8000/books

### GET BOOK
GET http://localhost:8000/books/21

### INSERT BOOK
POST http://localhost:8000/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjQzMDYwMjgsImlkIjoyNiwibmFtZSI6Ik1hbWF0MTIzIn0.0fAS1bWIEgOzpJAX1tzrWoi2XvsFaSw0mt4-lA_uoMQ

{
    "title": "Bat Man 123",
    "author": "Jack Spar 123",
    "description": "Buku Bat man"
}

### DELETE BOOK
DELETE  http://localhost:8000/books/3

### PUT BOOK
PUT http://localhost:8000/books/2
Content-Type: application/json

{
    "title": "Aqua Man",
    "author": "Peri",
    "description": "Sang Raja lautan"
}