name: ci-cd
on: 
  push:
    branches:
      - master
env:
  GO_VERSION: 1.19
jobs:
  test:
    name: checks
    runs-on: ubuntu-latest
    steps:
    - name: set up go ${{env.GO_VERSION}}
      uses: actions/setup-go@v2 # v2 automatically adds GOBIN to PATH
      with:
        go-version: ${{env.GO_VERSION}}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run tests
      run: go test -v ./...
    - name: Check code coverage
      run: |
        go test -coverprofile=coverage.tmp.out ./...
        cat coverage.tmp.out | grep -v _mock.go > coverage.out
        go tool cover -html=coverage.out -o coverage.html
    - name: Upload coverage report to codecov.io
      run: ./scripts/codecov-upload.sh -f ./coverage.out -y ./codecov.yml -n coverage-report -F
    - name: Add coverage.out to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: coverage-out
        path: ./coverage.out
    - name: Add coverage.html to artifacts
      uses: actions/upload-artifact@v1
      with:
        name: coverage-html
        path: ./coverage.html
