name: ci-cd
on: 
  push:
    branches:
      - master
env:
  GO_VERSION: 1.19.2
jobs:
  test:
    name: checks
    runs-on: ubuntu-latest
    steps:
    - name: set up go ${{env.GO_VERSION}}
      uses: actions/setup-go@v3 # v2 automatically adds GOBIN to PATH
      with:
        go-version: ${{env.GO_VERSION}}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run tests
      run: go test -v ./...